### PR TITLE
fix: add auth header for stacks hook

### LINKED ISSUE #438: Chainhook is not forwarding the auth header to webhook url for stacks predicates
@micaiah There is a customer who is saying their auth header is not being added to the requests to their webhook url
Here is what platform is sending to chainhook api
```
{
    "name": "For localhost",
    "chain": "stacks",
    "version": 1,
    "networks": {
        "testnet": {
            "if_this": {
                "scope": "contract_call",
                "method": "create-gig",
                "contract_identifier": "ST2GW18TVQR75W1VT53HYGBRGKFRV5BFYNAYRBHF4.Cerulean-marketplace-v1"
            },
            "end_block": null,
            "then_that": {
                "http_post": {
                    "url": "https://update-zero.vercel.app/api/chainhook/updateGig",
                    "authorization_header": "abcdefg"
                }
            },
            "start_block": 107542,
            "decode_clarity_values": true,
            "expire_after_occurrence": null
        }
    }
}
```
Here is the customer's predicate json, which I uploaded using the file upload feature
```
{
  "name": "For localhost",
  "chain": "stacks",
  "version": 1,
  "networks": {
    "testnet": {
      "if_this": {
        "scope": "contract_call",
        "method": "create-gig",
        "contract_identifier": "ST2GW18TVQR75W1VT53HYGBRGKFRV5BFYNAYRBHF4.Cerulean-marketplace-v1"
      },
      "end_block": null,
      "then_that": {
        "http_post": {
          "url": "https://update-zero.vercel.app/api/chainhook/updateGig",
          "authorization_header": "abcdefg"
        }
      },
      "start_block": 107542,
      "decode_clarity_values": true,
      "expire_after_occurrence": null
    }
  }
}
```
It seems like platform is sending the data correctly. Can you check this from your side please?
Here is the link to the thread in Discord - https://discord.com/channels/621759717756370964/1086336958546071666/1161310372700110879
cc @sabby

### PR DESCRIPTION
**Pull request by MicaiahReid**
Fixes #438

### CODE REVIEW

**Review by lgalabru — APPROVED** [review]
Thanks @MicaiahReid!

File: components/chainhook-sdk/src/chainhooks/stacks/mod.rs [hunk 1]
```diff
@@ -829,6 +829,7 @@ pub fn handle_stacks_hook_action<'a>(
                 client
                     .request(method, &host)
                     .header("Content-Type", "application/json")
+                    .header("Authorization", http.authorization_header.clone())
```
Comment (sabbyanandan) [inline components/chainhook-sdk/src/chainhooks/stacks/mod.rs:832]: If we aren't already logging these backed by a DEBUG flag or equivalent, and if it is not an expensive operation, could we consider logging what's being packaged up as part of the response or server-side re-direct?

Comment (sabbyanandan) [reply components/chainhook-sdk/src/chainhooks/stacks/mod.rs:832]: So I realize if the redirect fails for any reason, that will be caught, and the details of what was attempted as the URL (including the header details) will be included in that error message, which is sufficient after all.

We don't have to explicitly log any further details, and with that, I will resolve this comment.
